### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by MAKMED1337** [MAKMED1337/PO#11]
We need to use some asset manager, to load sprites/animations(also fix current gif bug/reimplement in a new format), probably based on https://libgdx.com/wiki/managing-your-assets.
We need to use some config file ("config.json" / "config.yaml") where we will be describe our assets. Every asset should be named, and have `path: str`, maybe (we can use path) `version: int | str`.
For each animation we should have some info about frames/read order/maybe gif.
We can use single sprites as different object than animation or use as an animation with 1 frame.
We need to add some `keypoints: [Point2D]`(for gun it would be holding position, muzzle position), as array and then parsing it, but it would be not very readable. Or we can add them as other properties (`{path: 'gun.png', frames: 1. holding_positon: (10, 10), muzzle: (11, 0)}`) into json/yaml/... . Or maybe `keypoints: Object` (`keypoints: {holding_positon: (10, 10), muzzle: (11, 0)}`).
Maybe? we need also to hold some extra information (as in previous case), but we can do it through loaders.
Then we should create some abstract loader, and loaders for guns/bullets/... .

**Comment by RyhorKoshman** [comment]
@MAKMED1337 what kind of gif bug do we have?

**Comment by MAKMED1337** [comment]
![image](https://github.com/MAKMED1337/PO/assets/50710486/85e21822-dcec-44df-916c-780cdba4f67e)
When gif is big (in the size), it starts to show some artifacts, like the line on the bottom.

**Comment by RyhorKoshman** [comment]
@MAKMED1337 I don't really understand how to make bullets come out from the muzzle (using correct texture of guns)

**Comment by MAKMED1337** [comment]
@RyhorKoshman in the config we would have keypoints(muzzle including) as coordinates on the texture, have you read the whole text ?

**Comment by RyhorKoshman** [comment]
@MAKMED1337 Yes, but there are a few problems, because our texture can be flipped and rotated.

**Comment by MAKMED1337** [comment]
@RyhorKoshman This logic should be calculated internally, like we are doing now. Maybe for rotation we need a center of a texture.
