### ISSUE TITLE
FUCK core multi-game

### ISSUE THREAD

**Issue by welleyth** [MAKMED1337/PO#2]
Currently the FUCK core seems to be able to handle only one instance of the game because of:

https://github.com/MAKMED1337/PO/blob/e202c9ad3d8fe6bcc38c409127cc3f1376aebf19/core/src/com/po/fuck/FUCK.java#L18

Can we make Initializer non-static and pass it all the instances we are planning to initialize for current core?

**Comment by MAKMED1337** [comment]
Do we need to create multiple instances of the same game in one executable ?

**Comment by welleyth** [comment]
In the future there could be made a multiplayer that would require several games running simultaneously.

**Comment by MAKMED1337** [comment]
I don't think so, maybe somewhere on the server side, but there are should be no sprites and so on.We can do a fork of running executable for running instance as a server.
