### ISSUE TITLE
Small refactor

### ISSUE THREAD

**Issue by dembanakh** [MAKMED1337/PO#24]
These are just small (not too important) suggestions. You don't have to apply them if you have a good reason not to, or even if you just don't like them😃

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/model/weapons/LaserBeam.java#L51-L53
you can cast immediately in if
```java
if (!(collidable instanceof Entity enemy)) continue;
this.tryDamage(enemy, delta*damage);
```

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/model/movement/Movement.java#L31-L33
```java
var selfOnly = !All.collidableCollection.collides(collidable.getCollision()).contains(collidable);
```

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/model/collections/SimpleCollection.java#L12-L13
```java
this::add,
this::remove)
```

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/model/collections/SimpleCollection.java#L8
Should this be an `abstract` class? (just to be clear)

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/model/collections/DrawableCollection.java#L12
Wouldn't [`SortedMap<Integer, List<Drawable>>`](https://docs.oracle.com/javase/8/docs/api/java/util/SortedMap.html) be a better fit here?

---

https://github.com/MAKMED1337/PO/blob/c4d8352fcbb86e1ffba5f3d673fa7f313cb62995/core/src/com/po/fuck/view/classdrawers/ClassDrawer.java#L5
this can be an `interface`

**Comment by MAKMED1337** [comment]
Use java naming.
Try to move all the constants from the objects, so it be easier to load through .properties.
