### ISSUE TITLE
Duplicating code

### ISSUE THREAD

**Issue by welleyth** [MAKMED1337/PO#3]
Are we able to avoid duplicating following code at any cost?

https://github.com/MAKMED1337/PO/blob/e202c9ad3d8fe6bcc38c409127cc3f1376aebf19/core/src/com/po/fuck/Player.java#L13-L15

**Comment by MAKMED1337** [comment]
Maybe if every class will `extends` from some "GameObject", but it will more hurt because we can do only 1 `extends` per class.
With current idea we can create some "static" constructor. Maybe there is some way with reflection and finding each class with some properties, but it could be even worse.

**Comment by MAKMED1337** [comment]
I think https://github.com/MAKMED1337/PO/issues/6 fixes this, so I am closing.
