### ISSUE TITLE
MouseTracking

### ISSUE THREAD

**Issue by welleyth** [MAKMED1337/PO#4]
If not to touch mouse after the start of the game, the weapon will not be visualized.

**Comment by MAKMED1337** [comment]
And what is desired behaviour ?

**Comment by welleyth** [comment]
Probably have fixed starting direction of the weapon, or, if it is possible, get the mouse position during creating a player. AFAIK now it updates a direction and draws a weapon each time the mouse moves

**Comment by MAKMED1337** [comment]
No, it draws and updates weapon each tick, it only updates aiming position when mouse moves.
