### ISSUE TITLE
Player model hides under models of enemies

### ISSUE THREAD

**Issue by welleyth** [MAKMED1337/PO#5]
Somehow try to change priority of player model to be always on top

**Comment by MAKMED1337** [comment]
Weapon should be on top of the player, because it looks better, but if you want to draw something on top of other you can overwrite `get_z()` from `Drawable`. Now it renders by the `z` coordinate, and in order of addition(the last will be on top).

**Comment by welleyth** [comment]
I meant a bit different, I have a new commit that implements the first minor part of enemies and they usually overlap the player. If we can just set „z” to some other value then it is ok

**Comment by MAKMED1337** [comment]
What should happen if enemy and player collides ? Probably the best idea, to disallow collision of 2 units. Or maybe draw objects that are further ghost'ish(only contour).
