### ISSUE TITLE
Add normal game object life system

### ISSUE THREAD

**Issue by MAKMED1337** [MAKMED1337/PO#6]
Add normal init and destroy, because current one are not very good.
Maybe using static methods, or interface.

**Comment by MAKMED1337** [comment]
@welleyth @RyhorKoshman what if we will use something like wrapper(like smart pointer in C++) to control object's lifespan ?
Not `Gun gun = new Glock();`, but `GameObject<Gun> gun = GameObject<Glock>();` ?
And what the name should be ?`GameObject`/`Life`, maybe some abbreviation, because we would use it frequently.

**Comment by welleyth** [comment]
That sounds like a one way of avoiding a lot of possible unwanted bugs. I would also suggest implementing "Managers" for all the events in the game. For example, create `interface Manager` and create `class BulletManager`, after create an `ArrayList<Manager> managers` in the core of the game.

**Comment by MAKMED1337** [comment]
@welleyth and what will these manages do ? And should we inherit any game objects(like gun, bullet) from them ?
Because I'm still thinking about inheritance(and construction through ifs) like now, but make creation and destruction in the other class.

**Comment by welleyth** [comment]
Currently we have a system, where we manually should call static field of the core to remove object from the active pool. What I have in mind is having a class that would have a permission to dispose and initialize (probably, update?) objects in the active pool. I could think about getting rid of static initializer we are currently having and replacing it with something.

**Comment by MAKMED1337** [comment]
@welleyth like my idea, but with using fabrics ? Or even without creating custom types ?
I think we need to use some custom type to indicate that object is managed, but I'm not sure about java caveats(syntax).

**Comment by welleyth** [comment]
> like my idea, but with using fabrics ?

I think yes. However, there is a flaw in it, as for now I have no vision how we should follow SOLID with single-usage here. Probably, have `ObjectFactory` that would initialize it somehow to `ObjectHandler`?

**Comment by welleyth** [comment]
> I think we need to use some custom type to indicate that object is managed

I am not sure if I understand clearly what you mean

**Comment by MAKMED1337** [comment]
> > I think we need to use some custom type to indicate that object is managed
> 
> I am not sure if I understand clearly what you mean

Like in the first example Not Gun gun = new Glock();, but GameObject<Gun> gun = GameObject<Glock>(); ?

**Comment by MAKMED1337** [comment]
> > like my idea, but with using fabrics ?
> 
> I think yes. However, there is a flaw in it, as for now I have no vision how we should follow SOLID with single-usage here. Probably, have `ObjectFactory` that would initialize it somehow to `ObjectHandler`?

I think LifetimeManager / other names, has only 1 responsibility.
