### ISSUE TITLE
Add teams

### ISSUE THREAD

**Issue by MAKMED1337** [MAKMED1337/PO#9]
Entity should have a team(or a TeamTag, without full info about a team), and a team collection, so enemies' AI could query it, some thing like `EntitiesCollection.getTeam(playersTeam) -> List<Entity>`, or maybe `getOtherTeam(currentTeam)`.
Other possible option is to add only two teams/tags "Players", "Enemies", but I don't like this variant, because with previous one we can add some interesting interaction.
Should we add teams only by a string name, or we should use a class ? Can we add teams' names into constants ?

**Comment by MAKMED1337** [comment]
We can also make bullets color coded by the team. But it should probably be a separate issue.

**Comment by RyhorKoshman** [comment]
@MAKMED1337 So we want every entity to have a team?

**Comment by MAKMED1337** [comment]
I think yes, because everything other should be a `GameObject`
